// Generated by reference/ink-pages/about-bc/build_bc.py. Do not edit by hand: change the
// script (or its TAKES) and run it again. The paintings of About B (the album) and C (the
// circle), October 7, 2026: GPT Image 2.5 on rice paper, the paper divided out so each multiplies
// onto the page's own paper; gold leaf as a light mask (`gold`) or a cut-out (the enso's dot).

export type Art = { src: string; width: number; height: number };
/** A gold-leaf cut-out, placed by fractions of its painting's width and height. */
export type Dot = Art & { left: number; top: number; size: number };
export const book = {
  src: "/images/about-bc/book-v1.webp",
  width: 1400,
  height: 581,
  gold: "/images/about-bc/book-v1-gold.webp",
} as const;

export const seedling = {
  src: "/images/about-bc/seedling-v1.webp",
  width: 1127,
  height: 1363,
  gold: "/images/about-bc/seedling-v1-gold.webp",
} as const;

export const desk = {
  src: "/images/about-bc/desk-v1.webp",
  width: 1400,
  height: 805,
} as const;

export const sequoia = {
  src: "/images/about-bc/sequoia-v1.webp",
  width: 1200,
  height: 1202,
  gold: "/images/about-bc/sequoia-v1-gold.webp",
} as const;

export const vignettes = {
  palms: {
    src: "/images/about-bc/palms-v1.webp",
    width: 480,
    height: 439,
  },
  bee: {
    src: "/images/about-bc/bee-v1.webp",
    width: 480,
    height: 490,
  },
  moon: {
    src: "/images/about-bc/moon-v1.webp",
    width: 480,
    height: 366,
  },
  letter: {
    src: "/images/about-bc/letter-v1.webp",
    width: 480,
    height: 426,
  },
} as const;

export const lamp = {
  src: "/images/about-bc/lamp-v1.webp",
  width: 1200,
  height: 792,
  gold: "/images/about-bc/lamp-v1-gold.webp",
} as const;

export const enso = {
  src: "/images/about-bc/enso-v1.webp",
  width: 1302,
  height: 1335,
  dot: {
    src: "/images/about-bc/enso-dot-v1.webp",
    width: 197,
    height: 205,
    left: 0.6959,
    top: 0.0127,
    size: 0.1513,
  },
  startDeg: 32.8,
} as const;

export const hills = {
  src: "/images/about-bc/hills-v1.webp",
  width: 2400,
  height: 341,
} as const;

export const glasses = {
  src: "/images/about-bc/glasses-v1.webp",
  width: 1200,
  height: 607,
} as const;

export const pool = {
  src: "/images/about-bc/pool-v1.webp",
  width: 968,
  height: 1407,
} as const;

export const dots = [
  {
    src: "/images/about-bc/dot-1-v1.webp",
    width: 360,
    height: 365,
  },
  {
    src: "/images/about-bc/dot-2-v1.webp",
    width: 360,
    height: 362,
  },
  {
    src: "/images/about-bc/dot-3-v1.webp",
    width: 360,
    height: 370,
  },
  {
    src: "/images/about-bc/dot-4-v1.webp",
    width: 338,
    height: 348,
  },
] as const;
