// Generated by reference/ink-pages/about/build_about.py. Do not edit by hand: change the
// script (or its TAKES) and run it again. The About page's paintings (Mo's design D, October 6,
// 2026): GPT Image 2.5 on rice paper, the paper divided out so each multiplies onto the page's
// own paper; gold leaf as cut-out pictures (the dots of the i) and as a light mask (the rings).

export type Art = { src: string; width: number; height: number };
/** A gold-leaf dot: its own picture, placed by fractions of its painting's width and height. */
export type Dot = Art & { left: number; top: number; size: number };
export const paperAged = "/images/about-ink/paper-aged-v1.webp" as const;

export const wipe = "/images/about-ink/wipe-v1.png" as const;

export const word = {
  src: "/images/about-ink/word-v1.webp",
  width: 1800,
  height: 668,
  dot: {
    src: "/images/about-ink/word-dot-v1.webp",
    width: 194,
    height: 198,
    left: 0.3284,
    top: 0.0347,
    size: 0.0961,
  },
} as const;

export const letters = {
  B: {
    src: "/images/about-ink/letter-b-v1.webp",
    width: 846,
    height: 1169,
  },
  i: {
    src: "/images/about-ink/letter-i-v1.webp",
    width: 287,
    height: 1183,
    dot: {
      src: "/images/about-ink/letter-i-dot-v1.webp",
      width: 264,
      height: 271,
      left: 0.0801,
      top: 0.0,
      size: 0.9199,
    },
  },
  G: {
    src: "/images/about-ink/letter-g-v1.webp",
    width: 900,
    height: 1059,
  },
  H: {
    src: "/images/about-ink/letter-h-v1.webp",
    width: 1069,
    height: 1125,
  },
} as const;

export const band = {
  src: "/images/about-ink/band-v1.webp",
  width: 2400,
  height: 302,
} as const;

export const pool = {
  src: "/images/about-ink/pool-v1.webp",
  width: 968,
  height: 1407,
} as const;

export const rings = {
  src: "/images/about-ink/rings-v1.webp",
  width: 1311,
  height: 1371,
  gold: "/images/about-ink/rings-v1-gold.webp",
} as const;

export const dots = [
  {
    src: "/images/about-ink/dot-1-v1.webp",
    width: 360,
    height: 365,
  },
  {
    src: "/images/about-ink/dot-2-v1.webp",
    width: 360,
    height: 362,
  },
  {
    src: "/images/about-ink/dot-3-v1.webp",
    width: 360,
    height: 370,
  },
  {
    src: "/images/about-ink/dot-4-v1.webp",
    width: 338,
    height: 348,
  },
] as const;
