// The homepage's "Curiosity, with references." list. Mo asked for real depth on September 24, 2026
// ("if we want to make that into a section, there'd better be more") and chose to add everything
// found. Every entry was checked on PubMed or loaded from its official page that day; the checks
// and the reasoning are in docs/research-list-candidates.md.
//
// Three filters: Science (how cells work and age), Ingredients (studies of ingredients used in a
// BiGH product, never of the finished product) and Guides (plain-language pages from public health
// institutes). The order within each group is the order shown. Plain titles and texts are copy
// keys with drafts in the five catalogs (reference/research-list/translations-research.cjs).
export const researchTypes = ["Science", "Ingredients", "Guides"] as const;
export type ResearchType = (typeof researchTypes)[number];

export type ResearchItem = {
  year: string;
  type: ResearchType;
  category: string;
  title: string;
  journal: string;
  text: string;
  url: string;
};

const P = "https://pubmed.ncbi.nlm.nih.gov/";

export const researchItems: ResearchItem[] = [
  // Science · how cells work and age
  {
    year: "2023",
    type: "Science",
    category: "Review · Biology of aging",
    title: "Healthy aging has many moving parts",
    journal: "Cell",
    text: "The Hallmarks of Aging review describes interconnected biological processes, including mitochondrial dysfunction. It provides a framework for learning about aging, not proof that a supplement slows it.",
    url: `${P}36599349/`,
  },
  {
    year: "2024",
    type: "Science",
    category: "Review · Antioxidants",
    title: "Antioxidants: how they really work",
    journal: "Nature Reviews",
    text: "Barry Halliwell reviews how antioxidants act in the body and where the evidence is weaker than the marketing. Free radicals also do useful jobs, and more antioxidant is not automatically better.",
    url: `${P}37714962/`,
  },
  {
    year: "2021",
    type: "Science",
    category: "Review · Exercise",
    title: "Exercise keeps mitochondria healthy",
    journal: "J Physiol",
    text: "A review of how physical activity builds and maintains healthy mitochondria in muscle. Movement remains the best-supported way to care for them.",
    url: `${P}31674658/`,
  },
  {
    year: "2018",
    type: "Science",
    category: "Review · Brain aging",
    title: "How the brain ages",
    journal: "Cell Metabolism",
    text: "Mattson and Arumugam describe the hallmarks of brain aging, including changes in energy metabolism and mitochondria. A map of the biology, not a treatment guide.",
    url: `${P}29874566/`,
  },
  {
    year: "2018",
    type: "Science",
    category: "Review · Stress",
    title: "Stress and your mitochondria",
    journal: "Psychosomatic Med",
    text: "Picard and McEwen propose a framework for how psychological stress affects mitochondria, drawn mostly from animal and cell studies. An idea being tested, not a settled fact.",
    url: `${P}29389735/`,
  },
  {
    year: "2016",
    type: "Science",
    category: "Review · Mitochondria",
    title: "Why mitochondria matter in aging",
    journal: "Molecular Cell",
    text: "Sun, Youle and Finkel review the evidence that mitochondrial decline is part of how cells age, and the open questions. Mechanisms, not a product claim.",
    url: `${P}26942670/`,
  },
  {
    year: "2015",
    type: "Science",
    category: "Review · Brain energy",
    title: "How the brain uses energy",
    journal: "Neuron",
    text: "Magistretti and Allaman explain how brain cells produce and share energy. Background on why mental energy is, at bottom, a cellular question.",
    url: `${P}25996133/`,
  },
  {
    year: "2012",
    type: "Science",
    category: "Cochrane review · Antioxidant supplements",
    title: "Antioxidant pills and living longer",
    journal: "Cochrane",
    text: "A review of 78 trials found no evidence that antioxidant supplements help people live longer, and a possible harm from beta-carotene and vitamin E at high doses. Balance for the whole topic.",
    url: `${P}22419320/`,
  },
  {
    year: "1956",
    type: "Science",
    category: "Classic paper · Free radicals",
    title: "Where the free-radical idea came from",
    journal: "J Gerontol",
    text: "Denham Harman's original proposal that free radicals drive aging. Parts of the theory have since been revised, but it started the field.",
    url: `${P}13332224/`,
  },
  // Ingredients · NuriCell (acetyl-L-carnitine, alpha-lipoic acid, creatine, choline)
  {
    year: "2002",
    type: "Ingredients",
    category: "Animal study · Ingredients",
    title: "Mitochondrial nutrients and the aging cell",
    journal: "PNAS",
    text: "Liu and colleagues studied acetyl-L-carnitine and R-alpha-lipoic acid in aging animals. This is part of the scientific background behind our interest in cellular health. It is not a clinical trial of NuriCell or evidence of a benefit in people.",
    url: `${P}11854529/`,
  },
  {
    year: "2002",
    type: "Ingredients",
    category: "Animal study · NuriCell ingredients",
    title: "A companion study of the same two nutrients",
    journal: "PNAS",
    text: "Hagen and colleagues, in a companion paper to the Liu study, tested acetyl-L-carnitine and lipoic acid in aging animals and measured metabolic function and oxidative stress. An animal study, not a human trial.",
    url: `${P}11854487/`,
  },
  {
    year: "2008",
    type: "Ingredients",
    category: "Review · NuriCell ingredients",
    title: "Dr. Liu on lipoic acid and the aging brain",
    journal: "Neurochem Res",
    text: "An overview by Dr. Jiankang Liu of how alpha-lipoic acid may support aging mitochondria and memory in animal studies. Written by our scientist; mostly animal work.",
    url: `${P}17605107/`,
  },
  {
    year: "2018",
    type: "Ingredients",
    category: "Review of trials · NuriCell ingredients",
    title: "Creatine and thinking in healthy adults",
    journal: "Exp Gerontol",
    text: "A systematic review of six small trials found creatine may help short-term memory and reasoning in healthy people, with mixed results elsewhere. Small studies; more work needed.",
    url: `${P}29704637/`,
  },
  {
    year: "2009",
    type: "Ingredients",
    category: "Review · NuriCell ingredients",
    title: "Lipoic acid as a supplement",
    journal: "BBA",
    text: "Shay and colleagues review what lipoic acid does in the body and what supplement studies suggest. Mechanisms are clearer than human benefits.",
    url: `${P}19664690/`,
  },
  {
    year: "2003",
    type: "Ingredients",
    category: "Pooled trials in patients · NuriCell ingredients",
    title: "Acetyl-L-carnitine in mild memory problems",
    journal: "Int Clin Psychopharm",
    text: "A meta-analysis of trials in people with mild cognitive impairment or mild Alzheimer's disease reported a benefit over placebo. Patients, not healthy adults; older trials.",
    url: `${P}12598816/`,
  },
  {
    year: "2003",
    type: "Ingredients",
    category: "Cochrane review · NuriCell ingredients",
    title: "Acetyl-L-carnitine for dementia",
    journal: "Cochrane",
    text: "A Cochrane review found no clear evidence of benefit in dementia. Shown beside the pooled trials above so both readings are visible.",
    url: `${P}12804452/`,
  },
  // Ingredients · Turmerific (Longvida curcumin)
  {
    year: "2015",
    type: "Ingredients",
    category: "Human trial · Turmerific ingredient",
    title: "Longvida curcumin in healthy older adults",
    journal: "J Psychopharmacol",
    text: "Cox and colleagues gave 60 healthy adults aged 60 to 85 the Longvida curcumin preparation for four weeks and reported changes in attention, working memory and mood. The same preparation Turmerific uses; a small, short study.",
    url: `${P}25277322/`,
  },
  {
    year: "2018",
    type: "Ingredients",
    category: "Human trial · Curcumin",
    title: "A curcumin form and memory",
    journal: "Am J Geriatr Psych",
    text: "Small and colleagues followed 40 adults without dementia for 18 months on a different curcumin preparation, Theracurmin, and reported memory changes. Another preparation, a small group.",
    url: `${P}29246725/`,
  },
  {
    year: "2017",
    type: "Ingredients",
    category: "Review · Curcumin",
    title: "Curcumin's chemistry problem",
    journal: "J Med Chem",
    text: "Nelson and colleagues explain why curcumin is poorly absorbed and why many laboratory results have not held up. A skeptical review, included on purpose.",
    url: `${P}28074653/`,
  },
  // Ingredients · Advanced OPC Formula (grape seed, pine bark)
  {
    year: "2011",
    type: "Ingredients",
    category: "Pooled trials · Advanced OPC ingredient",
    title: "Grape seed extract and blood pressure",
    journal: "J Am Diet Assoc",
    text: "A meta-analysis of nine trials found a modest drop in systolic blood pressure and heart rate with grape seed extract, and no change in cholesterol. Modest effects in short trials.",
    url: `${P}21802563/`,
  },
  {
    year: "2010",
    type: "Ingredients",
    category: "Human trial · Advanced OPC ingredient",
    title: "Pine bark extract: a trial that found nothing",
    journal: "Arch Intern Med",
    text: "A 12-week trial of pine bark extract in 130 adults found no effect on blood pressure, cholesterol or other heart-risk markers. A null result, shown because honesty matters.",
    url: `${P}20876405/`,
  },
  // Ingredients · Green Bee Propolis
  {
    year: "2020",
    type: "Ingredients",
    category: "Review · Green propolis",
    title: "Artepillin C, the key compound in green propolis",
    journal: "Fitoterapia",
    text: "A review of the chemistry, absorption and laboratory findings for artepillin C, the compound Brazilian green propolis is known for. Mostly laboratory studies; few human trials.",
    url: `${P}33152464/`,
  },
  {
    year: "2021",
    type: "Ingredients",
    category: "Review · Propolis",
    title: "What has been tested about propolis",
    journal: "Nutrients",
    text: "A review of experimental studies on propolis from different regions. Composition varies with the plants bees visit, so results do not transfer between products.",
    url: `${P}34444688/`,
  },
  // Ingredients · Nature Calm (CoQ10, theanine, phosphatidylserine)
  {
    year: "2018",
    type: "Ingredients",
    category: "Review · Nature Calm ingredient",
    title: "CoQ10 in aging",
    journal: "Front Physiol",
    text: "A review of coenzyme Q10's role in cellular energy and what supplement trials in aging and disease have shown. Mixed trial results.",
    url: `${P}29459830/`,
  },
  {
    year: "2019",
    type: "Ingredients",
    category: "Human trial · Nature Calm ingredient",
    title: "L-theanine and everyday stress",
    journal: "Nutrients",
    text: "Thirty healthy adults took L-theanine for four weeks and reported fewer stress-related symptoms than on placebo. Small and short; healthy volunteers.",
    url: `${P}31623400/`,
  },
  {
    year: "2010",
    type: "Ingredients",
    category: "Human trial · Nature Calm ingredient",
    title: "Phosphatidylserine and memory complaints",
    journal: "J Clin Biochem Nutr",
    text: "Seventy-eight older Japanese adults with memory complaints took soybean phosphatidylserine for six months; those with lower scores at the start improved more. One trial, one group.",
    url: `${P}21103034/`,
  },
  // Guides · plain-language pages from public health institutes
  {
    year: "GUIDE",
    type: "Guides",
    category: "Science explained",
    title: "What are mitochondria?",
    journal: "NHGRI",
    text: "A short introduction from the National Human Genome Research Institute. Mitochondria are structures in cells that help turn energy from food into energy that cells can use.",
    url: "https://www.genome.gov/genetics-glossary/Mitochondria",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Evidence overview",
    title: "Antioxidants: what the evidence says",
    journal: "NCCIH",
    text: "The National Center for Complementary and Integrative Health explains what is known about antioxidant supplements and where the evidence is uncertain. The role of a nutrient in the body does not automatically establish a benefit from supplementation.",
    url: "https://www.nccih.nih.gov/health/antioxidant-supplements-what-you-need-to-know",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Healthy aging",
    title: "What do we know about healthy aging?",
    journal: "NIA",
    text: "The National Institute on Aging sums up what research says about staying healthy as we age: movement, food, sleep, connection, and what remains uncertain.",
    url: "https://www.nia.nih.gov/health/healthy-aging/what-do-we-know-about-healthy-aging",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Brain health",
    title: "Cognitive health and older adults",
    journal: "NIA",
    text: "The National Institute on Aging on what helps keep thinking skills as we age, and which claims are not backed by evidence.",
    url: "https://www.nia.nih.gov/health/brain-health/cognitive-health-and-older-adults",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Supplements",
    title: "Dietary supplements: what you need to know",
    journal: "NIH ODS",
    text: "The Office of Dietary Supplements explains how supplements are regulated, how to read a label, and the questions to ask before taking one.",
    url: "https://ods.od.nih.gov/factsheets/WYNTK-Consumer/",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Ingredient explained",
    title: "Turmeric",
    journal: "NCCIH",
    text: "What is known about turmeric and curcumin, how well they are absorbed, and safety notes, from the National Center for Complementary and Integrative Health.",
    url: "https://www.nccih.nih.gov/health/turmeric",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Ingredient explained",
    title: "Grape seed extract",
    journal: "NCCIH",
    text: "A plain summary of the research on grape seed extract and its safety.",
    url: "https://www.nccih.nih.gov/health/grape-seed-extract",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Ingredient explained",
    title: "Choline",
    journal: "NIH ODS",
    text: "A consumer fact sheet on choline: what it does, how much people need, and food sources.",
    url: "https://ods.od.nih.gov/factsheets/Choline-Consumer/",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Ingredient explained",
    title: "Carnitine",
    journal: "NIH ODS",
    text: "A fact sheet for health professionals on carnitine, including acetyl-L-carnitine, and what studies have looked at.",
    url: "https://ods.od.nih.gov/factsheets/Carnitine-HealthProfessional/",
  },
  {
    year: "GUIDE",
    type: "Guides",
    category: "Science explained",
    title: "Antioxidants",
    journal: "MedlinePlus",
    text: "The National Library of Medicine's plain introduction to antioxidants and free radicals.",
    url: "https://medlineplus.gov/antioxidants.html",
  },
];
