// Generated by reference/ink-pages/nuricell/build_nuricell.py. Do not edit by hand: change
// the script (or its TAKES) and run it again. NuriCell's ink paintings (October 9, 2026): GPT
// Image 2.5 on rice paper, the paper divided out so each multiplies onto the page's own paper;
// gold leaf as a light mask (`gold`). sum.centres: its three numbers, as fractions of its width.
export const nuricellArt = {
  lanternUnlit: {
    src: "/images/products/nuricell/ink/lantern-unlit-v1.webp",
    width: 1100,
    height: 2091,
  },
  lanternLit: {
    src: "/images/products/nuricell/ink/lantern-lit-core-v2.webp",
    width: 1100,
    height: 2091,
    gold: "/images/products/nuricell/ink/lantern-lit-core-v2-gold.webp",
  },
  capsule: {
    src: "/images/products/nuricell/ink/capsule-v1.webp",
    width: 1200,
    height: 1135,
    gold: "/images/products/nuricell/ink/capsule-v1-gold.webp",
  },
  books: {
    src: "/images/products/nuricell/ink/books-v1.webp",
    width: 1100,
    height: 982,
  },
  liu: {
    src: "/images/products/nuricell/ink/liu-v1.webp",
    width: 1000,
    height: 1476,
  },
  breakfast: {
    src: "/images/products/nuricell/ink/breakfast-v1.webp",
    width: 1100,
    height: 1167,
    gold: "/images/products/nuricell/ink/breakfast-v1-gold.webp",
  },
  sum: {
    src: "/images/products/nuricell/ink/sum-v1.webp",
    width: 1400,
    height: 326,
    numbers: [3, 30, 90],
    centres: [0.1017, 0.4433, 0.8467],
  },
  stroke: {
    src: "/images/products/nuricell/ink/stroke-v1.webp",
    width: 1400,
    height: 211,
  },
} as const;
